### ISSUE TITLE
🐛 BUG: Replicated components fail to load

### ISSUE THREAD

**Issue by jonathantneal** [snowpackjs/astro#1054]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Replicated components fail to load. When reassigning a component to another variable in an `.astro` file, Astro throws an error about a `tag` variable that is missing a `toLowerCase` function.

You can see the error @ https://codesandbox.io/s/github/jonathantneal/astro-component-replication-issue
You can checkout the reproduction @ https://github.com/jonathantneal/astro-component-replication-issue

```astro
---
import Example from "../component/example.astro";

const Replicate = Example
---
<Replicate />
```

```log
[executing astro] TypeError: tag.toLowerCase is not a function
    at _h (/_snowpack/pkg/astro.dist.internal.h.v0.18.9.js:16:11)
    at _h.next (<anonymous>)
    at Function.from (<anonymous>)
    at Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.18.9.js:49:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
    at async Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.18.9.js:45:20)
    at async Promise.all (index 1)
    at async Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.18.9.js:45:20)
    at async Promise.all (index 1)
    at async Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.18.9.js:45:20)
    at async Promise.all (index 0)
    at async Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.18.9.js:45:20)
    at async Object.__renderPage (/_astro/src/pages/index.astro.js:85:27)
    at async load (~/astro-component-issue/node_modules/astro/dist/runtime.js:165:16)
    at async Server.<anonymous> (~/astro-component-issue/node_modules/astro/dist/dev.js:21:20)
``` 

### Steps to Reproduce

1. Checkout and prepare this repository.
   ```sh
   npm install
   npm start
   ```
2. Visit the development website, `http://localhost:3000/`.
3. See the error, `TypeError: tag.toLowerCase is not a function`.

### Link to Minimal Reproducible Example (Optional)

https://github.com/jonathantneal/astro-component-replication-issue

**Comment by jasikpark** [comment]
Is the identifier that's imported a Symbol or something? Or is it just naive regex matching?

**Comment by natemoo-re** [comment]
Confirming that this is fixed in the new compiler! [See REPL example](https://astro.build/play#eyJpbm1lbW9yeTovL21vZGVsL3NyYy9wYWdlcy9QYWdlLmFzdHJvIjoiLS0tXG5pbXBvcnQgQ29tcG9uZW50IGZyb20gJ0AvQ29tcG9uZW50LmFzdHJvJztcbmNvbnN0IFJlcGxpY2F0ZWQgPSBDb21wb25lbnQ7XG4tLS1cbjxodG1sIGxhbmc9XCJlblwiPlxuICA8aGVhZD5cbiAgICA8bWV0YSBjaGFyc2V0PVwiVVRGLThcIj5cbiAgICA8dGl0bGU+QXN0cm8gUGxheWdyb3VuZDwvdGl0bGU+XG4gICAgPHN0eWxlPlxuICAgICAgbWFpbiB7XG4gICAgICAgIGNvbG9yOiByZWQ7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cbiAgPC9oZWFkPlxuICA8Ym9keT5cbiAgICA8bWFpbj5cbiAgICAgIDxSZXBsaWNhdGVkPndvcmtpbmcgZXhhbXBsZSE8L1JlcGxpY2F0ZWQ+XG4gICAgPC9tYWluPlxuICA8L2JvZHk+XG48L2h0bWw+XG4iLCJpbm1lbW9yeTovL21vZGVsL3NyYy9jb21wb25lbnRzL0NvbXBvbmVudC5hc3RybyI6IjxoMT5IZWxsbyA8c2xvdCAvPjwvaDE+In0=)
