### ISSUE TITLE
🐛 BUG: Cannot using pnpm?

### ISSUE THREAD

**Issue by mzaini30** [snowpackjs/astro#1115]
### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

I got this error:

```
(node:4502) UnhandledPromiseRejectionWarning: Error: Cannot find module '@astrojs/renderer-vue' from '/home/zen/latihan/coba-astro/'
    at Function.resolveSync [as sync] (/home/zen/latihan/coba-astro/node_modules/.pnpm/resolve@1.20.0/node_modules/resolve/lib/sync.js:102:15)
    at resolveDependency (file:///home/zen/latihan/coba-astro/node_modules/.pnpm/astro@0.19.0-next.2/node_modules/astro/dist/config_manager.js:42:48)
    at file:///home/zen/latihan/coba-astro/node_modules/.pnpm/astro@0.19.0-next.2/node_modules/astro/dist/config_manager.js:49:40
    at Array.map (<anonymous>)
    at ConfigManager.buildRendererInstances (file:///home/zen/latihan/coba-astro/node_modules/.pnpm/astro@0.19.0-next.2/node_modules/astro/dist/config_manager.js:43:64)
    at createSnowpack (file:///home/zen/latihan/coba-astro/node_modules/.pnpm/astro@0.19.0-next.2/node_modules/astro/dist/runtime.js:203:49)
    at createRuntime (file:///home/zen/latihan/coba-astro/node_modules/.pnpm/astro@0.19.0-next.2/node_modules/astro/dist/runtime.js:289:13)
    at dev (file:///home/zen/latihan/coba-astro/node_modules/.pnpm/astro@0.19.0-next.2/node_modules/astro/dist/dev.js:17:25)
    at runCommand (file:///home/zen/latihan/coba-astro/node_modules/.pnpm/astro@0.19.0-next.2/node_modules/astro/dist/cli.js:80:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:4502) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Steps to Reproduce

1. mkdir coba-astro
2. cd coba-astro
3. pnpm init -y
4. pnpm i -D astro@next
5. Edit `package.json` to this:

	```json
	{
	  "name": "coba-astro",
	  "version": "1.0.0",
	  "description": "",
	  "main": "index.js",
	  "scripts": {
	    "dev": "astro dev",
	    "build": "astro build"
	  },
	  "keywords": [],
	  "author": "",
	  "license": "ISC",
	  "devDependencies": {
	    "astro": "^0.19.0-next.2"
	  }
	}
	```

6. pnpm dev
7. I got error

### Link to Minimal Reproducible Example (Optional)

https://github.com/mzaini30/astro-error

**Comment by mzaini30** [comment]
Solved with `pnpm i --shamefully-hoist`

**Comment by jasikpark** [comment]
Hmm did you find that in the docs? I can't seem to find it.. that is the recommended way to use Astro with npm though. https://docs.astro.build/installation - i feel like it used to be here?

**Comment by mzaini30** [comment]
@jasikpark I use pnpm for my daily use 😅

**Comment by jasikpark** [comment]
Sorry, autocorrected `pnpm` to `npm` whoops
