### ISSUE TITLE
🐛 BUG: Example "Docs" fails to run

### ISSUE THREAD

**Issue by MattWilcox** [snowpackjs/astro#1325]
### What package manager are you using?

npm

### What operating system are you using?

OSX

### Describe the Bug

Following instructions does not result in a working demo of the "Docs" example.

### Steps to Reproduce

1. `npm init astro -- --template docs`
2. `npm install`
3. `npm run dev`
4. Error

```nitro/astro/docs 
➜ npm init astro -- --template docs

Need to install the following packages:
  create-astro
Ok to proceed? (y) y

Welcome to Astro! (create-astro v0.5.2)
If you encounter a problem, visit https://github.com/snowpackjs/astro/issues to search or file a new issue.

> Prepare for liftoff.
> Gathering mission details...
✔ Using template's default renderers › Preact
> Copying project files...
✔ Done!

Next steps:
  1: npm install (or pnpm install, yarn, etc)
  2: git init && git add -A && git commit -m "Initial commit" (optional step)
  3: npm start (or pnpm, yarn, etc)

To close the dev server, hit Ctrl-C

Stuck? Visit us at https://astro.build/chat


nitro/astro/docs is 📦 v0.0.1 via ⬢ v14.17.0 took 6s 
➜ npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 827 packages, and audited 828 packages in 44s

190 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

nitro/astro/docs is 📦 v0.0.1 via ⬢ v14.17.0 took 44s 
➜ npm run dev                      

> @example/docs@0.0.1 dev
> astro dev

[21:08:22] [snowpack] Hint: run "snowpack init" to create a project config file. Using defaults...
[21:08:22] [snowpack] Welcome to Snowpack! Because this is your first time running
this project, Snowpack needs to prepare your dependencies. This is a one-time step
and the results will be cached for the lifetime of your project. Please wait...
[21:08:23] [snowpack] + astro/dist/internal/__astro_component.js@0.20.4
[21:08:23] [snowpack] └── shorthash@0.0.2 (dedupe)
[21:08:23] [snowpack] └── estree-util-value-to-estree@1.2.0 (dedupe)
[21:08:23] [snowpack]   └── is-plain-obj@3.0.0
[21:08:23] [snowpack] └── astring@1.7.5 (dedupe)
[21:08:24] [snowpack] + astro/dist/internal/element-registry.js@0.20.4
[21:08:24] [snowpack] + astro/dist/internal/fetch-content.js@0.20.4
[21:08:24] [snowpack] + astro/dist/internal/__astro_slot.js@0.20.4
[21:08:24] [snowpack] + astro/dist/internal/__astro_hoisted_scripts.js@0.20.4
[21:08:24] [snowpack] + prismjs@1.24.1
[21:08:25] [snowpack] + @astrojs/renderer-preact/server@0.2.1
[21:08:25] [snowpack] └── preact@10.5.14 (dedupe)
[21:08:25] [snowpack] └── preact-render-to-string@5.1.19 (dedupe)
[21:08:25] [snowpack] + @astrojs/renderer-preact/client@0.2.1
[21:08:25] [snowpack] + preact/jsx-runtime@10.5.14
[21:08:25] [snowpack] + @astrojs/renderer-react/server@0.2.0
[21:08:25] [snowpack] └── react@17.0.2 (dedupe)
[21:08:26] [snowpack]   └── object-assign@4.1.1
[21:08:26] [snowpack] └── react-dom/server.js@17.0.2 (dedupe)
[21:08:26] [snowpack] + @astrojs/renderer-react/client@0.2.0
[21:08:26] [snowpack] └── react-dom@17.0.2 (dedupe)
[21:08:28] [snowpack]   └── scheduler@0.20.2
[21:08:28] [snowpack]   └── scheduler/tracing@0.20.2
[21:08:28] [snowpack] + react@16.14.0
[21:08:28] [snowpack] └── prop-types/checkPropTypes@15.7.2
[21:08:28] [snowpack] + react/jsx-runtime@16.14.0
[21:08:29] [snowpack] + react-dom@16.14.0
(node:70918) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/mattwilcox/nitro/astro/docs/node_modules/.cache/snowpack/build/react-dom@16.14.0/react-dom/server.js'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:70918) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:70918) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

nitro/astro/docs is 📦 v0.0.1 via ⬢ v14.17.0 took 9s 
```

**Comment by jasikpark** [comment]
Hmmm what error did you get? I tested out the current docs example, and it built for me, so maybe we need to change something in your dev environment? https://codesandbox.io/s/github/snowpackjs/astro/tree/main/examples/docs

**Comment by jasikpark** [comment]
😅 I also failed to get that error when building on my local machine with node version 14.7.0.. let me know if you sorted something out, or what I can do to help!

**Comment by MattWilcox** [comment]
I was on 14.17.0 ... downloaded the latest stable Node as 14.17.6 and tried it all again... it works.

Seems like a bug of some sort in node 14.17.0? Or perhaps one of the snowpack packages was missing or corrupt? Either way, sorted. Thanks!

**Comment by MattWilcox** [comment]
Nope, my bad, was on the wrong repo. Just tried again on the "docs" project with newly updated Node... still fails.

```nitro/astro/docs is 📦 v0.0.1 via ⬢ v14.17.6 
➜ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> bufferutil@4.0.3 install /Users/mattwilcox/nitro/astro/docs/node_modules/bufferutil
> node-gyp-build


> utf-8-validate@5.0.5 install /Users/mattwilcox/nitro/astro/docs/node_modules/utf-8-validate
> node-gyp-build


> esbuild@0.12.25 postinstall /Users/mattwilcox/nitro/astro/docs/node_modules/esbuild
> node install.js


> esbuild@0.9.7 postinstall /Users/mattwilcox/nitro/astro/docs/node_modules/snowpack/node_modules/esbuild
> node install.js


> svelte-preprocess@4.9.1 postinstall /Users/mattwilcox/nitro/astro/docs/node_modules/svelte-preprocess
> echo "[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc..."

[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc...
removed 5 packages, updated 822 packages and audited 823 packages in 10.319s

190 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


nitro/astro/docs is 📦 v0.0.1 via ⬢ v14.17.6 took 11s 
➜ npm run dev

> @example/docs@0.0.1 dev /Users/mattwilcox/nitro/astro/docs
> astro dev

[11:36:46] [snowpack] Hint: run "snowpack init" to create a project config file. Using defaults...
[11:36:46] [snowpack] Welcome to Snowpack! Because this is your first time running
this project, Snowpack needs to prepare your dependencies. This is a one-time step
and the results will be cached for the lifetime of your project. Please wait...
(node:74952) UnhandledPromiseRejectionWarning: Error: Package "react" not found. Have you installed it? 
    at Object.resolveEntrypoint (/Users/mattwilcox/nitro/astro/docs/node_modules/esinstall/lib/entrypoints.js:175:15)
    at PackageSourceLocal.buildPackageImport (/Users/mattwilcox/nitro/astro/docs/node_modules/snowpack/lib/cjs/sources/local.js:424:40)
    at async PackageSourceLocal.prepare (/Users/mattwilcox/nitro/astro/docs/node_modules/snowpack/lib/cjs/sources/local.js:227:13)
    at async startServer (/Users/mattwilcox/nitro/astro/docs/node_modules/snowpack/lib/cjs/commands/dev.js:240:9)
    at async createSnowpack (file:///Users/mattwilcox/nitro/astro/docs/node_modules/astro/dist/runtime.js:273:14)
    at async createRuntime (file:///Users/mattwilcox/nitro/astro/docs/node_modules/astro/dist/runtime.js:293:7)
    at async dev (file:///Users/mattwilcox/nitro/astro/docs/node_modules/astro/dist/dev.js:17:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:74952) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:74952) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by MattWilcox** [comment]
Rebooted my machine, emptied the directory, tried again... worked. I have no idea why.

**Comment by jasikpark** [comment]
i guess we'll never know! i'm glad it's working for you now :)

**Comment by jasikpark** [comment]
Hmm this seems to be similar to #1311, mind copying your error log over to the older issue so we can sort out what's up?

It seems like Snowpack might be tripping over react-dom? 🤔
