### ISSUE TITLE
🐛 BUG: using `Astro.fetchContent('../**/*.md')` inside `getStaticPaths() {...}` throws `Error: Parse error`

### ISSUE THREAD

**Issue by SarcevicAntonio** [snowpackjs/astro#1363]
### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Inside my `src/pages/tag/[tag].astro` there is the following `getStaticPaths` function block:
```js
  export async function getStaticPaths() {
    /** hardcoded const array works */
    let tags = [
      "tag-everyone-has",
      "other",
      "test",
      "test-two",
      "other-two",
    ]

    /** This throws errors */
    const allPosts = Astro.fetchContent('../**/*.md');
    tags = [...new Set(allPosts.flatMap(entry => [...entry.tags]))];

    return tags.map(tag => {return { params: {tag}}});
  }
```

Using `Astro.fetchContent('../**/*.md');` works inside .astro files normally (see `src/pages/tag/index.astro`), but seemingly not inside `getStaticPaths`.

### Steps to Reproduce

**NOTE: I have created a Minimal Reproducible Example with my exact logic**

1. `npm init astro` using minimal template
2. create two folders inside pages with markdown files (sub-blog-one and sub-blog-one)
3. in those markdown files add a title and some tags to the frontmatter
3. create `src/pages/tag/index.astro` and create a page that fetches all posts, rips all tags out and shows them in a list
4. create `src/pages/tag/[tag].astro` and inside getStaticProps use the same logic to fetches all posts, rip all tags out and map that to the desired return structure
5. Error! Going to `http://localhost:3000/tag/test` I get error `Error: Parse error @:34:26`.

Full Console Output at Dev Time:
```
[access] /tag/test
[executing astro] Error: Parse error @:34:26
    at parse (C:\Users\LinkPlay\dev\astro-fetchcontent-inside-getstaticpaths\node_modules\snowpack\node_modules\es-module-lexer\dist\lexer.cjs:1:402)
    at scanCodeImportsExports (C:\Users\LinkPlay\dev\astro-fetchcontent-inside-getstaticpaths\node_modules\snowpack\lib\cjs\rewrite-imports.js:21:29)
    at transformEsmImports (C:\Users\LinkPlay\dev\astro-fetchcontent-inside-getstaticpaths\node_modules\snowpack\lib\cjs\rewrite-imports.js:37:27)
    at Object.transformFileImports (C:\Users\LinkPlay\dev\astro-fetchcontent-inside-getstaticpaths\node_modules\snowpack\lib\cjs\rewrite-imports.js:108:16)       
    at FileBuilder.resolveImports (C:\Users\LinkPlay\dev\astro-fetchcontent-inside-getstaticpaths\node_modules\snowpack\lib\cjs\build\file-builder.js:116:48)     
    at async Object.loadUrl (C:\Users\LinkPlay\dev\astro-fetchcontent-inside-getstaticpaths\node_modules\snowpack\lib\cjs\commands\dev.js:641:39)
    at async load (C:\Users\LinkPlay\dev\astro-fetchcontent-inside-getstaticpaths\node_modules\snowpack\lib\cjs\commands\dev.js:217:28)
    at async C:\Users\LinkPlay\dev\astro-fetchcontent-inside-getstaticpaths\node_modules\snowpack\lib\cjs\ssr-loader\index.js:60:28
    at async Object.importModule (C:\Users\LinkPlay\dev\astro-fetchcontent-inside-getstaticpaths\node_modules\snowpack\lib\cjs\ssr-loader\index.js:165:26)        
    at async load (file:///C:/Users/LinkPlay/dev/astro-fetchcontent-inside-getstaticpaths/node_modules/astro/dist/runtime.js:95:17)
    at async Server.<anonymous> (file:///C:/Users/LinkPlay/dev/astro-fetchcontent-inside-getstaticpaths/node_modules/astro/dist/dev.js:21:20) {
  idx: 972
}
[access] /500
```

### Link to Minimal Reproducible Example (Optional)

https://github.com/SarcevicAntonio/astro-fetchcontent-inside-getstaticpaths

**Comment by NickKelly1** [comment]
I get the same error from running fetchContent twice on two separate .md blobs within the pre-render script of an .astro file

**Comment by matthewp** [comment]
I was able to confirm. This is due to #863 which has a better description, so I'm going to close this one and reopen that one.
