### ISSUE TITLE
🐛 BUG: JSX code as prop attribute for React components is broken in Astro files

### ISSUE THREAD

**Issue by jablonski** [snowpackjs/astro#1482]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When using a React component with some legit JSX code as prop like

` <Container content={<p>Lorem</p>} />`

in an Astro-File, Astro throws the following error:

`Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.
    at mapIntoArray (/_snowpack/pkg/react.v17.0.2/common/index-ed20953e.js:1042:17)
    at mapChildren (/_snowpack/pkg/react.v17.0.2/common/index-ed20953e.js:1071:3)
    at toArray (/_snowpack/pkg/react.v17.0.2/common/index-ed20953e.js:1121:10)
    at ReactDOMServerRenderer.renderDOM (/_snowpack/pkg/react-dom.server.v17.0.2.js:4241:18)
    at ReactDOMServerRenderer.render (/_snowpack/pkg/react-dom.server.v17.0.2.js:3779:21)
    at ReactDOMServerRenderer.read (/_snowpack/pkg/react-dom.server.v17.0.2.js:3675:29)
    at Object.renderToStaticMarkup (/_snowpack/pkg/react-dom.server.v17.0.2.js:4291:27)
    at Object.renderToStaticMarkup (/_snowpack/pkg/@astrojs.renderer-react.server.v0.2.1.js:45:22)
    at __astro_component_internal (/_snowpack/pkg/astro.dist.internal.__astro_component.v0.20.8.js:199:48)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)`

This pattern works without problems in React, Gatsby & Next and should work in Astro too.

### Steps to Reproduce

1. Create a React component in components/Container.jsx:

```
import React from 'react';

export default function Container({ content }) {
    return (
        <div>{content}</div>
    );
}

```

2. Use React component in pages/test.astro:

```
---
import Container from '../components/Container.jsx';
---
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
</head>
<body>
    <Container content={<p>Lorem</p>} />
</body>
</html>
```

**Comment by matthewp** [comment]
This is because React and Astro are not the same thing, so you cannot pass Astro tags to React; React doesn't recognize them. Children are special cased and we convert the children to React vdom before passing to React.

This issue explains the difficulty of trying to make this work: https://github.com/snowpackjs/astro/issues/681#issuecomment-906410275

As explained in that comment, due to the complexity an RFC will be needed to proceed.
