### ISSUE TITLE
🐛 BUG: Failed when trying to start a development server on the Minimal/Starter template

### ISSUE THREAD

**Issue by thatcatdrout** [snowpackjs/astro#1645]
### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

When i tried to `yarn start` a development server on the Minimal / Starter template i get this error:

`yarn run v1.22.15
$ astro dev
/home/catdrout/Desktop/UltimateWebsite/node_modules/@astrojs/language-server/dist/check.js:46
            text: this.docManager.get(uri)?.getText() || '',
                                           ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/catdrout/Desktop/UltimateWebsite/node_modules/@astrojs/language-server/dist/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Please help**

### Steps to Reproduce

1. `npm init astro` using template <Minimal> or <Starter>
2. ... yarn 
3. ...yarn start
4. Error! Describe what went wrong (and what was expected instead)... So i got a syntax error somewhere in node_modules: `/home/catdrout/Desktop/UltimateWebsite/node_modules/@astrojs/language-server/dist/check.js:46
            text: this.docManager.get(uri)?.getText() || '',
                                           ^

SyntaxError: Unexpected token '.'

It should just have started a development server`

### Link to Minimal Reproducible Example (Optional)

https://github.com/thatcatdrout/astro-bug

**Comment by arecvlohe** [comment]
I also encountered the same error. I `rm -rf node_modules` but the error was still there afterward. I will try and tinker some more and figure out if something else is wrong.

**Comment by matthewp** [comment]
Thanks! Would love a reproduction here. The one in the original issue is 404ing now.

**Comment by thatcatdrout** [comment]
i dont use astro anymore cuz its too hard for me to use so i will close this issue!

**Comment by matthewp** [comment]
Sorry to hear that! Please join discord if you ever wind up trying again and we'd be happy to help you learn.
