### ISSUE TITLE
🐛 BUG: Astro in a yarn workspaces monorepo results in missing @snowpack plugin dependencies

### ISSUE THREAD

**Issue by michaelwarren1106** [snowpackjs/astro#1704]
### What package manager are you using?

yarn

### What operating system are you using?

mac

### Describe the Bug

Im working in a yarn workspaces enabled monorepo. I tried to init a new astro template install, and the `@snowpack/plugin-postcss` dependency wasnt found and resulted in an `Unhandled promise rejection` error

```
(node:47551) UnhandledPromiseRejectionWarning: Error: Cannot find module '@snowpack/plugin-postcss' from '/Users/<FOLDER>/'
    at Function.resolveSync [as sync] (/Users/<FOLDER>/node_modules/resolve/lib/sync.js:102:15)
    at resolveDependency (file:///Users/<FOLDER>/node_modules/astro/dist/runtime.js:198:46)
    at createSnowpack (file:///Users/<FOLDER>/node_modules/astro/dist/runtime.js:253:9)
    at async createRuntime (file://Users/<FOLDER>/node_modules/astro/dist/runtime.js:303:7)
    at async dev (file:///Users/<FOLDER>/node_modules/astro/dist/dev.js:17:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:47551) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:47551) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 1.90s.
```

### Steps to Reproduce

1. `npm init astro` using template docs
2. cd docs
3. yarn
4. Unhandled promise rejection

forcing all astro dependencies to NOT hoist to the monorepo root using the following in the package.json of the workspace package seems to work:
```
workspaces: {
   nohoist: ["**/*"]
}
```
If no astro dependencies are hoisted, `yarn start` succeeds as expected.

if i try to limit the hoist to `"nohoist": ["**/@snowpack/*"]` the `yarn start` script still fails with a different plugin (`plugin-sass`), so it doesnt seem to be limited to `plugin-postcss`

**Comment by natemoo-re** [comment]
This is a known issue with PnP package managers like `yarn > 1` and `pnpm`. It's why we include an [`.npmrc`](https://github.com/snowpackjs/astro/blob/main/examples/minimal/.npmrc) file in our examples. 

Hopefully the `astro@next` release fixes this—we moved from Snowpack to Vite. But it's possible this is still a limitation in Vite!

If you'd like to open a PR to add a note to our documentation and/or example templates, that would be much appreciated.

**Comment by michaelwarren1106** [comment]
Im using yarn v1, not v2, so imo its still an issue?

I think its just a matter of how astro looks for its plugins? seems like they are expected to not be hoisted, so when they are, they aren't found?

**Comment by FredKSchott** [comment]
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.
