### ISSUE TITLE
🐛 BUG: `Unexpected "return"` error with astro@0.21.0-next.0 and astro-seo

### ISSUE THREAD

**Issue by jonasmerlin** [snowpackjs/astro#1719]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When using Astro SEO with astro@0.21.0-next.0, you get the following error:

```
6:29:13 AM [vite] Error when evaluating SSR module /node_modules/astro-seo/src/index.js?v=3f58f290:
Error: Transform failed with 1 error:
<path to project>/node_modules/astro-seo/src/SEO.astro:120:0: error: Unexpected "return"
    at failureErrorWithLog (<path to project>/node_modules/esbuild/lib/main.js:1493:15)
    at <path to project>/node_modules/esbuild/lib/main.js:1282:29
    at <path to project>/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (<path to project>/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (<path to project>/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
6:29:13 AM [vite] Error when evaluating SSR module <path to project>/src/pages/index.astro:
Error: Transform failed with 1 error:
<path to project>/node_modules/astro-seo/src/SEO.astro:120:0: error: Unexpected "return"
    at failureErrorWithLog (<path to project>/node_modules/esbuild/lib/main.js:1493:15)
    at <path to project>/node_modules/esbuild/lib/main.js:1282:29
    at <path to project>/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (<path to project>/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (<path to project>/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

The code at line 120 of Astro SEO (the line the error identifies as the problem) is the following:

```javascript
        {openGraph.optional.description ? (
```

In context: 

```javascript
function generateOpenGraphOptionalTags(props: Props) {
  if (openGraph && openGraph.optional) {
    return (
      <Fragment>
        {openGraph.optional.audio ? (
          <meta property="og:audio" content={openGraph.optional.audio} />
        ) : null}
        {openGraph.optional.description ? (
          <meta
            property="og:description"
            content={openGraph.optional.description}
          />
        ) : null}
        {openGraph.optional.determiner ? (
          <meta
            property="og:determiner"
            content={openGraph.optional.determiner}
          />
        ) : null}
        {openGraph.optional.locale ? (
          <meta property="og:locale" content={openGraph.optional.locale} />
        ) : null}
        {openGraph.optional.localeAlternate?.map((locale) => (
          <meta property="og:locale:alternate" content={locale} />
        ))}
        {openGraph.optional.siteName ? (
          <meta property="og:site_name" content={openGraph.optional.siteName} />
        ) : null}
        {openGraph.optional.video ? (
          <meta property="og:video" content={openGraph.optional.video} />
        ) : null}
      </Fragment>
    );
  } else {
    return null;
  }
}
```

Since this code worked with astro 0.20.X and I can't identify the problem, my current best guess is that the issue is on the astro side of things, maybe in the new compiler?

Thanks for taking a look and sorry if I'm missing anything really obvious here!

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. `npm install astro-seo`
3. add `import { SEO } from 'astro-seo'` to index.astro
4. use `<SEO /> anywhere anywhere
5. run `npm run dev`
6. Open `localhost:3000` in browser
7. Error! (Would have expected no error)

Alternatively:
1. pull the reproduction repo
2. run `npm install`
3. run `npm run dev`
4. Open `localhost:3000` in browser
5. Error! (Would have expected no error)

### Link to Minimal Reproducible Example (Optional)

https://github.com/jonasmerlin/astro-0.21-seo-repro

**Comment by natemoo-re** [comment]
We unfortunately had to remove support for components inside of frontmatter in v0.21! This was a bit unexpected, but we kept running into bugs and undefined behavior as a result of this accidental feature. 

The main issue is that Astro components no longer adhere to a simple `(props, children) => VNode` interface which authors might expect. This is really the only breaking change we're making in this release, but we haven't put out any sort of migration guide yet. The gist of it is to use separate `.astro` files.

Going to close this. PR opened against `astro-seo`, where we can continue the discussion if necessary. https://github.com/jonasmerlin/astro-seo/pull/24
