### ISSUE TITLE
🐛 BUG: JSX not allowed in .astro frontmatter

### ISSUE THREAD

**Issue by IanVS** [snowpackjs/astro#1857]
### What version of `astro` are you using?

0.21.0-next.5

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

This was working in astro 0.20.12.  I have a component that takes a `variant` prop, and renders a different icon depending on that prop:

```
---
const { href, variant } = Astro.props;

let icon;
if (variant === 'Twitter') {
  icon = <span class="fab fa-twitter"/>;
}
else if (variant === 'Medium') {
  icon = <span class="fab fa-medium-m"/>;
} else if (variant === 'LinkedIn') {
  icon = <span class="fab fa-linkedin"/>;
}
---

<style lang="scss">
  .SocialCircle {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 46px;
    width: 46px;
    border-radius: 50%;
    color: white;
    background-color: var(--theme-button);
    transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;

    &:hover {
      text-decoration: none;
      color: white;
      background-color: var(--theme-button-dim);
    }
  }
</style>

<a href={href} class="SocialCircle" aria-label={`Visit Defined Networking on ${variant}`} title={variant}>
  {icon}
</a>
```

I attempted to update to the latest `next` release, but I'm now getting a 500 page:

```
/Users/ianvs/code/defined/www/src/components/atoms/SocialCircle.astro: Expected ">" but found "class"
  27 |   }
  29 |   .hero {
  30 |     max-width: var(--max-width);
  31 |     margin: 0 auto;

Error: Transform failed with 1 error:
/Users/ianvs/code/defined/www/src/components/atoms/SocialCircle.astro:28:15: error: Expected ">" but found "class"
    at failureErrorWithLog (/Users/ianvs/code/defined/www/node_modules/esbuild/lib/main.js:1493:15)
    at /Users/ianvs/code/defined/www/node_modules/esbuild/lib/main.js:1282:29
    at /Users/ianvs/code/defined/www/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/Users/ianvs/code/defined/www/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/Users/ianvs/code/defined/www/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

Also note that the lines of code shown are not actually the correct location with the error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fefvl9?file=src/component.astro

**Comment by IanVS** [comment]
Looks like this was an intentional breaking change: https://github.com/snowpackjs/astro-compiler-next/pull/144

**Comment by XantreGodlike** [comment]
Is it still planing? Because it would be great to write mini component in the frontmatter.

**Comment by haochenx** [comment]
bump
