### ISSUE TITLE
Node 12 supported?

### ISSUE THREAD

**Issue by rajasegar** [snowpackjs/astro#343]
Does Astro support Node 12? Because I am getting some errors like 
```
npm start

> @astrojs/starter-kit@0.0.1 start /home/boot/Public/www/astro-hello-world
> astro dev

(node:10761) ExperimentalWarning: The ESM module loader is experimental.
file:///home/boot/Public/www/astro-hello-world/node_modules/.pnpm/astro@0.12.10/node_modules/astro/dist/cli.js:1451
import {clearCache} from "snowpack";
        ^^^^^^^^^^
SyntaxError: The requested module 'snowpack' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'snowpack';
const {clearCache} = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:143:20)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:84:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @astrojs/starter-kit@0.0.1 start: `astro dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @astrojs/starter-kit@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/boot/.npm/_logs/2021-06-09T01_44_46_289Z-debug.log
```
I see that in package.json there is a volta config that specifies only Node 14 and the CI matrix is [14.x, 16.x]

**Comment by samuelhorn** [comment]
I got about the same message on node 14 as well.

#349

**Comment by FredKSchott** [comment]
This happens when Node.js doesn't support ESM. The official support range is: 
```
"node": "^12.20.0 || ^14.13.1 || >=16.0.0".
```

Most likely you're on a version of node.js 12 or 14 that's behind when ESM support was added. See: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

Added PR #415 to create installation warnings if you're on an older version.
