### ISSUE TITLE
Syntax error in .astro file when trying to render multiple nodes in map

### ISSUE THREAD

**Issue by SoulDrivenDev** [snowpackjs/astro#405]
Syntax example:

```
<ul>
{items.map(item => (
<li>{item.first}</li>
<li>{item.second}</li>
))}
</ul>
```

This is a contrived example, but my actual use case is for multiple nodes of an SVG. I also tried using a fragment node to wrap the contents of the map, but received an error that the fragment is not defined.

**Comment by ejb** [comment]
Not sure if this is the same bug, but I don't seem to be able to use JSX within the head matter.

This works within an `.astro` file:
```jsx
<ul>
  {['foo','bar'].map(x => <li>{x}</li>)}
</ul>
```

This does not:
```jsx
---
let items = ['foo','bar'].map(x => <li>{x}</li>);
---
<ul>
  {items}
</ul>
```

Neither does this:

```js
---
let item = <li>{x}</li>;
---
<ul>
  {item}
</ul>
```

Here are the full details of the 500 error:
```
Error: Parse error @:16:27
    at parse$n (/Users/Elliot/Sites/ejb.github.io/node_modules/snowpack/lib/index.js:113435:379)
    at scanCodeImportsExports (/Users/Elliot/Sites/ejb.github.io/node_modules/snowpack/lib/index.js:114662:29)
    at transformEsmImports (/Users/Elliot/Sites/ejb.github.io/node_modules/snowpack/lib/index.js:114678:27)
    at Object.transformFileImports (/Users/Elliot/Sites/ejb.github.io/node_modules/snowpack/lib/index.js:114749:16)
    at FileBuilder.resolveImports (/Users/Elliot/Sites/ejb.github.io/node_modules/snowpack/lib/index.js:163324:45)
    at Object.loadUrl (/Users/Elliot/Sites/ejb.github.io/node_modules/snowpack/lib/index.js:182840:39)
    at load (/Users/Elliot/Sites/ejb.github.io/node_modules/snowpack/lib/index.js:182430:28)
    at /Users/Elliot/Sites/ejb.github.io/node_modules/snowpack/lib/index.js:175004:32
    at async Promise.all (index 3)
    at initializeModule (/Users/Elliot/Sites/ejb.github.io/node_modules/snowpack/lib/index.js:175003:17)
    at load (file:///Users/Elliot/Sites/ejb.github.io/node_modules/astro/src/runtime.ts:95:17)
    at Server.<anonymous> (file:///Users/Elliot/Sites/ejb.github.io/node_modules/astro/src/dev.ts:33:20)
```

**Comment by natemoo-re** [comment]
Discussing this with the team! We'll likely need a built-in `Fragment` component.

**Comment by SoulDrivenDev** [comment]
Just saw this; works like a charm :)
