### ISSUE TITLE
🐛 BUG: Astro dev server with different ports don't select different HMR ports

### ISSUE THREAD

**Issue by ewatch** [snowpackjs/astro#429]
### Bug Report: Quick Checklist

- [x] I am on the latest version of Astro & all plugins.
- [x] I am on an ESM Node.js version (`v14.16.1`)
- [x] I use package manager: (npm/yarn).
- [x] I run Astro on OS: (Mac).

### Describe the bug

Starting multiple astro dev servers with different ports configured `astro.config.mjs` lead to an error message.

### Steps to reproduce

1. Create two astro projects with `npm init astro`
2. Change one of the projects `astro.config.mjs` to use  `port: 3001`
3. Start the project with the default config `npm start`
4. Start the project with the changed with `npm start` as well
5. Astro Dev Server doesn't startup and shows an error message

```
Error: listen EADDRINUSE: address already in use :::12321
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at new WebSocketServer (/Users/jan-martinfruehwacht/Development/JavaScript/astro-projects/my-astro-project/node_modules/snowpack/lib/index.js:166782:20)
    at new EsmHmrEngine (/Users/jan-martinfruehwacht/Development/JavaScript/astro-projects/my-astro-project/node_modules/snowpack/lib/index.js:167148:15)
    at Object.startHmrEngine (/Users/jan-martinfruehwacht/Development/JavaScript/astro-projects/my-astro-project/node_modules/snowpack/lib/index.js:167352:23)
    at startServer (/Users/jan-martinfruehwacht/Development/JavaScript/astro-projects/my-astro-project/node_modules/snowpack/lib/index.js:183004:15)
    at createSnowpack (file:///Users/jan-martinfruehwacht/Development/JavaScript/astro-projects/my-astro-project/node_modules/astro/src/runtime.ts:429:14)
    at createRuntime (file:///Users/jan-martinfruehwacht/Development/JavaScript/astro-projects/my-astro-project/node_modules/astro/src/runtime.ts:454:7)
    at dev (file:///Users/jan-martinfruehwacht/Development/JavaScript/astro-projects/my-astro-project/node_modules/astro/src/dev.ts:27:19)
```
### Expected behavior

Both servers should be able to start up properly.
And reachable through different ports:
`http://localhost:3000` and `http://localhost:3001`

**Comment by sam-parsons** [comment]
The problem seems to be located in `packages/astro/snowpack-plugin.cjs` with the declaration of DEFAULT_HMR_PORT, hardcoded with the value 12321.  Multiple instances of astro dev server will use the same default HMR port.

I am interested in solving this, though it is my first issue and would appreciate a small amount of guidance.

A library could be used to determine whether the current default HMR port is in use - if so then dynamically serially allocate an open port (in this case port 12322, 12323, ...).  I think that's unnecessary overhead for a niche situation.  

The snowpack plugin does have access to  the `astroConfig` object which has a port number value for the `devOptions` property.  A compliment approach could be used where the HMR port would be coupled to the devServer port in some way.  If devServer is 3000, HMR could be 12321 - if devServer is 3002, HMR could be 12323 - 3004, 12325 ...  The con is that the possible HMR port range could be just as random as the input dev server.

**Comment by natemoo-re** [comment]
I think @matthewp tackled this already, but the fix hasn't been released yet! Can you confirm Matthew?

**Comment by matthewp** [comment]
No, I tackled an issue where we weren't using the HMR port defined in a snowpack config. That doesn't enable multiple dev servers going at once.

I think the same problem is going to exist for HMR and the http server. We do indeed need to be able to dynamically assign a port for both of those, to pull this issue off.

**Comment by jasikpark** [comment]
It would be great to have dynamic port assignment for both the dev server and HMR when the port in the config file is in use!

**Comment by jasikpark** [comment]
Replicated on astro@1.17.2. Tried to run `astro-docs` and `astro/www` at the same time, with the docs on port `3001`

```
✗  yarn workspace www start
yarn workspace v1.22.10
yarn run v1.22.10
$ astro dev
[02:30:19] [snowpack] Ready!
node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::12321
    at Server.setupListenHandle [as _listen2] (node:net:1305:16)
    at listenInCluster (node:net:1353:12)
    at Server.listen (node:net:1440:7)
    at new WebSocketServer (/Users/calebjasik/Github/astro/node_modules/snowpack/node_modules/ws/lib/websocket-server.js:75:20)
    at new EsmHmrEngine (/Users/calebjasik/Github/astro/node_modules/snowpack/lib/cjs/hmr-server-engine.js:24:15)
    at Object.startHmrEngine (/Users/calebjasik/Github/astro/node_modules/snowpack/lib/cjs/dev/hmr.js:14:23)
    at startServer (/Users/calebjasik/Github/astro/node_modules/snowpack/lib/cjs/commands/dev.js:801:17)
    at async createSnowpack (file:///Users/calebjasik/Github/astro/packages/astro/dist/runtime.js:320:14)
    at async createRuntime (file:///Users/calebjasik/Github/astro/packages/astro/dist/runtime.js:340:7)
    at async dev (file:///Users/calebjasik/Github/astro/packages/astro/dist/dev.js:18:19)
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (node:events:394:28)
    at emitErrorNT (node:net:1332:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 12321
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/Cellar/node/16.4.2/bin/node
Arguments: /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js start
Directory: /Users/calebjasik/Github/astro/www
Output:
```

**Comment by jasikpark** [comment]
Hopefully, this can be fixed for both required ports where they will automagically pick an unused port if the defaults are already in use.

**Comment by mihkeleidast** [comment]
This should be fairly easy to implement using something like [get-port](https://www.npmjs.com/package/get-port). I've used it before successfully, although there are some [weird cases](https://github.com/sindresorhus/get-port/issues/31) where it still fails for some reason. Could I maybe take a stab at this?

**Comment by jasikpark** [comment]
Feel free to spin up a PR for it! That'd be great!
