### ISSUE TITLE
🐛 BUG: Astro fails when parsing JavaScript within `pre` tags

### ISSUE THREAD

**Issue by austincrim-pfg** [snowpackjs/astro#573]
### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When including JavaScript code in a `pre` or `code` block in a `.astro` file
```html
<pre>
  <code>
if ('Notification' in window) {
  // do stuff
}
  </code>
</pre>
```
it fails to parse the page with this error:

```bash
[17:09:03] [snowpack] Build Result Error: There was a problem with a file build result.
[executing astro] CompileError [ParseError]: Unexpected block closing tag
    at error (/Users/C097645/repos/perusing-the-platform/node_modules/@astrojs/parser/src/utils/error.ts:40:15)
    at Parser.error (/Users/C097645/repos/perusing-the-platform/node_modules/@astrojs/parser/src/parse/index.ts:108:5)
    at mustache (/Users/C097645/repos/perusing-the-platform/node_modules/@astrojs/parser/src/parse/state/mustache.ts:71:14)
    at new Parser (/Users/C097645/repos/perusing-the-platform/node_modules/@astrojs/parser/src/parse/index.ts:54:15)
    at parse (/Users/C097645/repos/perusing-the-platform/node_modules/@astrojs/parser/src/parse/index.ts:226:18)
    at convertAstroToJsx (file:///Users/C097645/repos/perusing-the-platform/node_modules/astro/src/compiler/index.ts:31:15)
    at transformFromSource (file:///Users/C097645/repos/perusing-the-platform/node_modules/astro/src/compiler/index.ts:91:20)
    at compileComponent (file:///Users/C097645/repos/perusing-the-platform/node_modules/astro/src/compiler/index.ts:110:24)
    at Object.load (/Users/C097645/repos/perusing-the-platform/node_modules/astro/snowpack-plugin.cjs:68:28)
    at runPipelineLoadStep (/Users/C097645/repos/perusing-the-platform/node_modules/snowpack/lib/index.js:122563:32)
    at Object.buildFile (/Users/C097645/repos/perusing-the-platform/node_modules/snowpack/lib/index.js:122763:24)
    at /Users/C097645/repos/perusing-the-platform/node_modules/snowpack/lib/index.js:163440:37
    at FileBuilder.build (/Users/C097645/repos/perusing-the-platform/node_modules/snowpack/lib/index.js:163452:32)
    at Object.loadUrl (/Users/C097645/repos/perusing-the-platform/node_modules/snowpack/lib/index.js:182858:17)
    at load (/Users/C097645/repos/perusing-the-platform/node_modules/snowpack/lib/index.js:182463:28)
    at load (file:///Users/C097645/repos/perusing-the-platform/node_modules/astro/src/runtime.ts:101:17)
    at Server.<anonymous> (file:///Users/C097645/repos/perusing-the-platform/node_modules/astro/src/dev.ts:33:20) {
  start: { line: 74, column: 3, character: 2597 },
  end: { line: 74, column: 3, character: 2597 },
  filename: '/Users/C097645/repos/perusing-the-platform/src/pages/notifications.astro',
  frame: '72:           <code>\n' +
    "73: if ('Notification' in window) {\n" +
    '74:   // do stuff\n' +
    '       ^\n' +
    '75: }\n' +
    '76:           </code>',
  __snowpackBuildDetails: { name: 'snowpack-astro', step: 'load' }
```

### Steps to Reproduce

1. `npm init astro`
2. add JavaScript code within a `pre` or `code` tag
3. `astro dev`
4. it throws the error lifted above

**Comment by MatsDahlin** [comment]
In this specific case it looks like the initial "/" in the comment is triggering the mustache parsers if-block check. 

There might be a bigger issue here that all javascript code inside the tags seems like it's getting evaluated instead of treated as text. 

I could look into this if needed but would like input about expected functionality.

For example, most people would probably expect it to just work like @austincrim-pfg here, and maybe some people would try to use a block inside of `<code>` or `<pre>` that _should_ be evaluated?

Like this:

```jsx
<code>
{`alert(${var_from_frontmatter});`}
</code>
```

**Comment by jasikpark** [comment]
Astro shouldn't error on "empty" embedded js expressions, right? `{// comment here}` should be valid though useless.

I'm aware that the correct way to comment is with HTML style comments, but it still seems like it should be valid, though that seems to be the raw error coming out of astro above.

**Comment by eyelidlessness** [comment]
> Astro shouldn't error on "empty" embedded js expressions, right? `{// comment here}` should be valid though useless.

I certainly hope not! `//` is a greedy token that extends to the end of the line, and should bypass `}`. But more importantly JS shouldn’t be executed in a child position at all.

**Comment by jasikpark** [comment]
> > Astro shouldn't error on "empty" embedded js expressions, right? `{// comment here}` should be valid though useless.
> 
> I certainly hope not! `//` is a greedy token that extends to the end of the line, and should bypass `}`. But more importantly JS shouldn’t be executed in a child position at all.

Good point 😅 Let me change that to `{/** comment here */}`.

**Comment by FredKSchott** [comment]
I think you need a value in the expression `{}` tag, so `{ /* foo */ }` is invalid but `{ /* foo */ null}` is valid.

**Comment by FredKSchott** [comment]
This is expected behavior, we replace `{}` with our custom expression handling which would break most JS. Some people might want to use that replacement inside of a code element.

Instead, you can put this inside of an expression of your own:

```
<pre>
  <code>{`
if ('Notification' in window) {
  // do stuff
}
  `}</code>
</pre>
