### ISSUE TITLE
🐛 BUG: Parse error when using <hr> tag

### ISSUE THREAD

**Issue by ilhamdev0** [snowpackjs/astro#590]
### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

I'm using Astro.fetchContent() and write my own code based on the first snippet in [this](https://github.com/snowpackjs/astro/blob/main/docs/reference/api-reference.md) to generate list of categories on my blog. here i'm passing the data as props from other component

```
---
const { data } = Astro.props;
---

<section>
    <h2>Categories</h2>
    
    {data.map(post =>
        <div>
            <a href='#'>{post.categories}</a>
            <span>(10)</span> //TODO:: number of post in categories
        </div>
        <hr>
    )}
</section>
```

but then it's failed
```
[dev server] Server started in 1146ms.
[dev server] Local: http://127.0.0.1:3000/
[01:30:00] [snowpack] watching for file changes...
[access] /
[parse-error]

 /home/eel/il_stuff/Project/myblog/src/layouts/sidebar/kanan.astro:13:30

 𝘅 Expected ")" but found "h"

     11 |             {data.map(post =>
     12 |                 <div>
   > 13 |                     <a href='#'>{post.kategori}</a>
        |                              ^
     14 |                     <span>(10)</span>
     15 |                 </div>
     16 |                 <hr>

(node:613858) UnhandledPromiseRejectionWarning: Error: Unable to compile expression
    at compileExpression (file:///home/eel/il_stuff/Project/myblog/node_modules/.pnpm/astro@0.15.1/node_modules/astro/src/compiler/codegen/index.ts:205:28)
    at Object.enter (file:///home/eel/il_stuff/Project/myblog/node_modules/.pnpm/astro@0.15.1/node_modules/astro/src/compiler/codegen/index.ts:541:24)
    at AsyncWalker.visit (file:///home/eel/il_stuff/Project/myblog/node_modules/.pnpm/estree-walker@3.0.0/node_modules/estree-walker/src/async.js:49:5)
    at AsyncWalker.visit (file:///home/eel/il_stuff/Project/myblog/node_modules/.pnpm/estree-walker@3.0.0/node_modules/estree-walker/src/async.js:86:6)
    at AsyncWalker.visit (file:///home/eel/il_stuff/Project/myblog/node_modules/.pnpm/estree-walker@3.0.0/node_modules/estree-walker/src/async.js:79:14)
    at AsyncWalker.visit (file:///home/eel/il_stuff/Project/myblog/node_modules/.pnpm/estree-walker@3.0.0/node_modules/estree-walker/src/async.js:79:14)
    at AsyncWalker.visit (file:///home/eel/il_stuff/Project/myblog/node_modules/.pnpm/estree-walker@3.0.0/node_modules/estree-walker/src/async.js:79:14)
    at asyncWalk (file:///home/eel/il_stuff/Project/myblog/node_modules/.pnpm/estree-walker@3.0.0/node_modules/estree-walker/src/index.js:34:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:613858) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

try restarting dev server but got same error in terminal, try console logging the props and no problem. But the strange thing is when i'm remove ```<hr>``` tag the error goes away and list of categories show up in website. trying to add back ```<hr>``` and it broke again

### Steps to Reproduce

.

**Comment by natemoo-re** [comment]
JS functions can only return a single object, so it's not possible to return multiple nodes like this. They must be wrapped in some type of container.

You can wrap them in a `Fragment` using the `<> </>` syntax [as outlined here](https://github.com/snowpackjs/astro/blob/main/docs/core-concepts/astro-components.md#fragments) or use an Array. Note that each element in any Array would require a trailing comma `[<div />, <hr>]`.

```
    {data.map(post => (
        <>
          <div>
            <a href='#'>{post.categories}</a>
            <span>(10)</span> //TODO:: number of post in categories
          </div>
          <hr>
        </>
    )}
```
