### ISSUE TITLE
🐛 BUG: __astro_element_registry is not defined

### ISSUE THREAD

**Issue by thepassle** [snowpackjs/astro#714]
### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

Astro seems to crash when conditionally rendering a custom element.

The following:
`MyComponent.astro`
```js
{true
  ? (<generic-disclosure></generic-disclosure>)
  : ''
}
```

results in:
```
[executing astro] ReferenceError: __astro_element_registry is not defined
    at Object.__render (/_astro/src/components/ApiTable.astro.js:35:528)
    at Object.renderToStaticMarkup (/_snowpack/pkg/astro.dist.internal.__astro_component.v0.17.2.js:23:32)
    at eval (/_snowpack/pkg/astro.dist.internal.__astro_component.v0.17.2.js:189:42)
    at async Promise.all (index 0)
    at Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.17.2.js:43:20)
    at async Promise.all (index 1)
    at Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.17.2.js:43:20)
    at async Promise.all (index 0)
    at Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.17.2.js:43:20)
    at Object.__renderPage (/_astro/src/pages/accordion.astro.js:52:27)
    at load (file:///Users/au87xu/generic-components/node_modules/astro/src/runtime.ts:229:17)
    at Server.<anonymous> (file:///Users/au87xu/generic-components/node_modules/astro/src/dev.ts:33:20)
```

I've tried rendering the custom element by itself (not in a ternary), and it works just fine. It's only when I add the ternary that I get this error.

E.g.: the following works:
```js
<generic-disclosure></generic-disclosure>
```

and:
```js
{true
  ? (<h1>sdf</h1>)
  : ''
}
```

As soon as I add the custom element to the ternary, it crashes.

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. ...
3. ...
4. ...
5. Error! Describe what went wrong (and what was expected instead)...

**Comment by natemoo-re** [comment]
Ah, thanks for opening an issue! We seem to not be scanning for custom elements in expressions at the moment, but can definitely add this.

**Comment by thepassle** [comment]
Not sure if this is the same problem, but this also breaks:
`alert.astro`:
```js
---
import Demo from '../components/Demo.astro';
---
<Demo title="default" code={() => (<generic-alert></generic-alert>)}
```
`Demo.astro.js`:
```js
---
import { Prism } from 'astro/components';
const {demo, title} = Astro.props;
---
<div class="demo">
  <h3>{title}:</h3>
  <details>
    <summary>Show code</summary>
    <Prism lang="html" code={demo()}/>

  </details>
  <hr />
</div>
```

**Comment by matthewp** [comment]
I'm away from a computer but this must be false for some reason https://github.com/snowpackjs/astro/blob/5814f2faca2a4b7a9d00f2895fe824ac786e6383/packages/astro/src/compiler/index.ts#L125

**Comment by matthewp** [comment]
My guess is that this line https://github.com/snowpackjs/astro/blob/5814f2faca2a4b7a9d00f2895fe824ac786e6383/packages/astro-parser/src/parse/read/expression.ts#L161

Has the ast.meta.features and we need to promote those to the parent ast.

**Comment by thepassle** [comment]
Just tried this with `"astro": "^0.17.3"`, and a clean `npm init astro` project. Given the following code:

```html
---
// Component Imports
import Tour from '../components/Tour.astro';
// You can import components from any supported Framework here!


// Component Script:
// You can write any JavaScript/TypeScript that you'd like here.
// It will run during the build, but never in the browser.
// All variables are available to use in the HTML template below.
let title = 'My Astro Site';

// Full Astro Component Syntax:
// https://docs.astro.build/core-concepts/astro-components/
---
<html lang="en">
<body>
    <script type="module" src="https://unpkg.com/@generic-components/components/alert.js"></script>
    {true ? <generic-alert>hi</generic-alert> : <h1>hi</h1>}
</body>
</html>
```

I still get the same error.

**Comment by thepassle** [comment]
The same thing happens in my actual project (where `alert.js` is in the public folder:

```html
---
import Layout from '../layouts/Layout.astro';
import Demo from '../components/Demo.astro';
import ApiTable from '../components/ApiTable.astro';
const component = 'generic-alert';
---
<Layout type="demo" title={component}>
  <script src="/alert.js" type="module"></script>
  
  <h1>generic-alert</h1>
  <a href="https://www.w3.org/TR/wai-aria-practices/#alert">WAI ARIA Practices</a>

  <p class="description">An alert is an element that displays a brief, important message in a way that attracts the
    user's attention without interrupting the user's task.</p>
  <h2>API:</h2>
  
  <ApiTable component={component}/>

  <h2>Usage:</h2>
  <p>Import the custom element and drop the it in your page.</p>

  <Demo title="default" demo={() => (<generic-alert>im an alert</generic-alert>)} />
</Layout>
```

**Comment by matthewp** [comment]
This hasn't been released yet. We're in a weird state where the main branch is the `next` tag so we can't easily release patches. But if you install `next` it should work. We intend to release 0.18 in the next couple of days.
