### ISSUE TITLE
🐛 BUG: ReferenceError: React is not defined

### ISSUE THREAD

**Issue by tronghieu60s** [snowpackjs/astro#818]
### What package manager are you using?

yarn

### What operating system are you using?

Windows 11

### Describe the Bug

I get the following error when I run `yarn start`:

```
ReferenceError: React is not defined
    at ReactCounter (/_astro/src/components/ReactCounter.js:8:3)
    at Tester (/_snowpack/pkg/@astrojs.renderer-react.server.v0.1.5.js:20:21)
    at processChild (/_snowpack/pkg/react-dom.server.v17.0.2.js:3338:14)
    at resolve (/_snowpack/pkg/react-dom.server.v17.0.2.js:3255:5)
    at ReactDOMServerRenderer.render (/_snowpack/pkg/react-dom.server.v17.0.2.js:3730:22)
    at ReactDOMServerRenderer.read (/_snowpack/pkg/react-dom.server.v17.0.2.js:3675:29)
    at Object.renderToStaticMarkup (/_snowpack/pkg/react-dom.server.v17.0.2.js:4291:27)
    at renderToStaticMarkup (/_snowpack/pkg/@astrojs.renderer-react.server.v0.1.5.js:45:22)
    at Object.check (/_snowpack/pkg/@astrojs.renderer-react.server.v0.1.5.js:31:3)
    at resolveRenderer (/_snowpack/pkg/astro.dist.internal.__astro_component.v0.17.3.js:118:40)
    at eval (/_snowpack/pkg/astro.dist.internal.__astro_component.v0.17.3.js:177:20)
```

When I use framework `Vue` everything works fine.

### Steps to Reproduce

1. `npm init astro` using template `Starter Kit (Generic)`
2. Select framework `React`
3. `yarn install`
4. `yarn start`
5. Run `http://127.0.0.1:3000/`
5. Error!

**Comment by FredKSchott** [comment]
@natemoo-re did all of the `next` renderers get released to `latest` as well when you released last night? You may need to do some cleanup there:

```
npm dist-tag add pkg@version latest # go back to latest
npm dist-tag add pkg@version next # set to new next
```

**Comment by matthewp** [comment]
Latest is still on 0.1.x:

```
latest: 0.1.5
next: 0.2.0-next.0
```

**Comment by FredKSchott** [comment]
okay great. Not sure what could be causing this then 🤔

**Comment by phiberber** [comment]
I am having the same issue with Astro's Solid example. 

```
ReferenceError: React is not defined
    at SolidCounter (/_astro/src/components/Counter.js:8:3)
    at eval (/_snowpack/pkg/solid-js.v1.0.4.js:1005:24)
    at untrack (/_snowpack/pkg/solid-js.v1.0.4.js:398:12)
    at Object.createComponent (/_snowpack/pkg/solid-js.v1.0.4.js:1005:10)
    at eval (/_snowpack/pkg/@astrojs.renderer-solid.server.v0.1.0-next.0.js:16:17)
    at escape (file:///C:/Users/Peixe/Documents/Projects/AstroSolid/node_modules/solid-js/web/dist/server.js:464:50)
    at file:///C:/Users/Peixe/Documents/Projects/AstroSolid/node_modules/solid-js/web/dist/server.js:255:44
    at file:///C:/Users/Peixe/Documents/Projects/AstroSolid/node_modules/solid-js/dist/server.js:427:14
    at createMemo (file:///C:/Users/Peixe/Documents/Projects/AstroSolid/node_modules/solid-js/dist/server.js:50:13)
    at file:///C:/Users/Peixe/Documents/Projects/AstroSolid/node_modules/solid-js/dist/server.js:423:17
    at new Promise (<anonymous>)
    at awaitSuspense (file:///C:/Users/Peixe/Documents/Projects/AstroSolid/node_modules/solid-js/dist/server.js:420:10)
    at Module.renderToStringAsync (file:///C:/Users/Peixe/Documents/Projects/AstroSolid/node_modules/solid-js/web/dist/server.js:255:24)
    at renderToStaticMarkup (/_snowpack/pkg/@astrojs.renderer-solid.server.v0.1.0-next.0.js:14:32)
    at Object.check (/_snowpack/pkg/@astrojs.renderer-solid.server.v0.1.0-next.0.js:9:26)
    at resolveRenderer (/_snowpack/pkg/astro.dist.internal.__astro_component.v0.17.3.js:118:40)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at eval (/_snowpack/pkg/astro.dist.internal.__astro_component.v0.17.3.js:177:20)
    ```

**Comment by FredKSchott** [comment]
Just confirming: is everyone on `latest` or `next`? Solid support is only on `next`, so this sounds like both issues are affecting `next`?

**Comment by phiberber** [comment]
When doing `npm init astro --template framework-solid`, it doesn't seem to download the latest commit from Github, so the version of astro was outdated in the package.json. Doing an `npm install astro@next` solved the issue (Astro was probably treating every JSX as a React Component, using React imports).
