### ISSUE TITLE
🐛 BUG: TSX broken since 0.18.0

### ISSUE THREAD

**Issue by radiosilence** [snowpackjs/astro#904]
### What package manager are you using?

yarn

### What operating system are you using?

MacOS

### Describe the Bug

If I create a TSX component `hi-man.tsx`: 

```tsx
import React from "react";
export default function HiMan() {
  return <div>hi, man</div>;
}
```

and import it like so in `index.astro`:

```astro
import HiMan from '../components/hi-man.tsx';
```

I get this error:

```
Error: Parse error @:3:29
    at parse (/Users/jc/Workspace/mw/my-astro-project/node_modules/snowpack/node_modules/es-module-lexer/dist/lexer.cjs:1:402)
    at scanCodeImportsExports (/Users/jc/Workspace/mw/my-astro-project/node_modules/snowpack/lib/cjs/rewrite-imports.js:21:29)
    at transformEsmImports (/Users/jc/Workspace/mw/my-astro-project/node_modules/snowpack/lib/cjs/rewrite-imports.js:37:27)
    at Object.transformFileImports (/Users/jc/Workspace/mw/my-astro-project/node_modules/snowpack/lib/cjs/rewrite-imports.js:108:16)
    at FileBuilder.resolveImports (/Users/jc/Workspace/mw/my-astro-project/node_modules/snowpack/lib/cjs/build/file-builder.js:116:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.loadUrl (/Users/jc/Workspace/mw/my-astro-project/node_modules/snowpack/lib/cjs/commands/dev.js:640:39)
    at async load (/Users/jc/Workspace/mw/my-astro-project/node_modules/snowpack/lib/cjs/commands/dev.js:217:28)
    at async /Users/jc/Workspace/mw/my-astro-project/node_modules/snowpack/lib/cjs/ssr-loader/index.js:60:28
    at async /Users/jc/Workspace/mw/my-astro-project/node_modules/snowpack/lib/cjs/ssr-loader/index.js:83:23
    at async initializeModule (/Users/jc/Workspace/mw/my-astro-project/node_modules/snowpack/lib/cjs/ssr-loader/index.js:88:39)
    at async Object.importModule (/Users/jc/Workspace/mw/my-astro-project/node_modules/snowpack/lib/cjs/ssr-loader/index.js:166:25)
    at async load (file:///Users/jc/Workspace/mw/my-astro-project/node_modules/astro/dist/runtime.js:76:17)
    at async Server.<anonymous> (file:///Users/jc/Workspace/mw/my-astro-project/node_modules/astro/dist/dev.js:21:20)
```

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. `yarn add react @types/react`
2. create TSX file above
3. import as above
4. yarn start
5. Get error above

### Link to Minimal Reproducible Example (Optional)

See above

**Comment by matthewp** [comment]
I'm not experiencing this issue. See here: https://github.com/matthewp/astro-bug-904

Is there something you're doing differently?

**Comment by FredKSchott** [comment]
@matthewp I'm seeing this issue in docs, on the `wip-search-bar` branch. Oddly enough, it seemed to be enabled by adding a second JSX renderer. That would make sense why introduced in 0.18.0, at least.

**Comment by radiosilence** [comment]
@matthewp here's my repo that has the problem, I'll see if I can find anything different

**Comment by radiosilence** [comment]
I think The problem was not including a typescript render - previously assumed that they were all included by default

**Comment by FredKSchott** [comment]
@matthewp and I debugged this and its a weirdddddd esbuild bug in the tsx loader. I have a workaround thought that seems to be working, submitting a PR now
