### ISSUE TITLE
🐛 BUG: Markdown `Expected "=>" but found end of file`

### ISSUE THREAD

**Issue by amatiasq** [snowpackjs/astro#932]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Markdown with `({})` in it causes exception:

```
 𝘅 Expected "=>" but found end of file

   > 1 | ({})
       |     ^

file:///Users/xxx/astro-bug-arrow-expected/node_modules/astro/dist/compiler/codegen/index.js:213
    throw new Error(`Unable to compile expression`);
          ^
```

### Steps to Reproduce

1. `git clone git@github.com:amatiasq/astro-bug-arrow-expected.git` using template <NAME>
2. `npm i`
3. `npm start`

## Expected result
It should render an HTML with `({})`

## Actual behaviour
```
[13:36:02] [snowpack] File changed: src/pages/index.md
[access] /
[parse-error] 

 /Users/xxx/astro-bug-arrow-expected/src/pages/index.md:1:7

 𝘅 Expected "=>" but found end of file

   > 1 | ({})
       |     ^

file:///Users/xxx/astro-bug-arrow-expected/node_modules/astro/dist/compiler/codegen/index.js:213
    throw new Error(`Unable to compile expression`);
          ^

Error: Unable to compile expression
    at compileExpression (file:///Users/xxx/astro-bug-arrow-expected/node_modules/astro/dist/compiler/codegen/index.js:213:11)
    at async Object.enter (file:///Users/xxx/astro-bug-arrow-expected/node_modules/astro/dist/compiler/codegen/index.js:464:24)
    at async AsyncWalker.visit (file:///Users/xxx/astro-bug-arrow-expected/node_modules/estree-walker/src/async.js:49:5)
    at async AsyncWalker.visit (file:///Users/xxx/astro-bug-arrow-expected/node_modules/estree-walker/src/async.js:86:6)
    at async AsyncWalker.visit (file:///Users/xxx/astro-bug-arrow-expected/node_modules/estree-walker/src/async.js:79:14)
    at async AsyncWalker.visit (file:///Users/xxx/astro-bug-arrow-expected/node_modules/estree-walker/src/async.js:79:14)
    at async asyncWalk (file:///Users/xxx/astro-bug-arrow-expected/node_modules/estree-walker/src/index.js:34:9)
```

### Link to Minimal Reproducible Example (Optional)

https://github.com/amatiasq/astro-bug-arrow-expected

**Comment by amatiasq** [comment]
As I side note: I tried to create the example as a gist but that's not possible because Gists don't support folders and Astro doesn't render components at the root (I tried `pages: '.'` in astro.config.mjs)

**Comment by mmarkelov** [comment]
@matthewp Yo can try to write it as string literal:
```
`({})`
```
this should be fine

**Comment by jasikpark** [comment]
Though honestly this is probably still a bug to fix since this should just be interpreted as markdown, unless you're using the Markdown component to render

**Comment by amatiasq** [comment]
This is the result when I use backticks:

![Screenshot 2021-07-29 at 18 15 03](https://user-images.githubusercontent.com/1533589/127527814-e4bd3033-8f18-4d6a-aba0-1291e004249c.png)

Generated html:
```html
<script>window.HMR_WEBSOCKET_PORT = 12321;</script><script type="module" src="/_snowpack/hmr-client.js"></script><p><code>(&amp;#123;})</code></p>
```

**Comment by aFuzzyBear** [comment]
This bug is still appearing inside the docs, I thought it got fixed, any comment on a resolution on this issue?

**Comment by natemoo-re** [comment]
Hmm, this isn't entirely **fixed** in the `astro@next` preview, but it is better! No more crash. [See reproduction](https://stackblitz.com/edit/github-x3dyfv-gduy21?file=src%2Fpages%2Findex.astro).

I'd still like to handle this case better. The output should just be `()` if there's no value inside the expression.
