### ISSUE TITLE
🐛 BUG: @vue/server-renderer not found

### ISSUE THREAD

**Issue by brycewray** [snowpackjs/astro#953]
### What package manager are you using?

npm

### What operating system are you using?

macOS 11.5.1

### Describe the Bug

Beginning with Astro 0.18.4, `npm run start` with `"@astrojs/renderer-vue"` listed in `renderers` in `astro.config.mjs` causes a crash with the following error message:

```bash
(node:57059) UnhandledPromiseRejectionWarning: Error: Package "@vue/server-renderer" not found. Have you installed it? 
    at Object.resolveEntrypoint (/Users/thewrays/astro-site/node_modules/esinstall/lib/entrypoints.js:175:15)
    at PackageSourceLocal.buildPackageImport (/Users/thewrays/astro-site/node_modules/snowpack/lib/cjs/sources/local.js:416:40)
    at async PackageSourceLocal.prepare (/Users/thewrays/astro-site/node_modules/snowpack/lib/cjs/sources/local.js:219:13)
    at async startServer (/Users/thewrays/astro-site/node_modules/snowpack/lib/cjs/commands/dev.js:240:9)
    at async createSnowpack (file:///Users/thewrays/astro-site/node_modules/astro/dist/runtime.js:321:14)
    at async createRuntime (file:///Users/thewrays/astro-site/node_modules/astro/dist/runtime.js:341:7)
    at async dev (file:///Users/thewrays/astro-site/node_modules/astro/dist/dev.js:17:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:57059) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:57059) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

Commenting out `"@astrojs/renderer-vue"` stops the crashing.

### Steps to Reproduce

1. `npm init astro` using a template that includes Vue.
2. `npm run start`
3. Instead of going into normal dev mode, the process crashes with the error message described above.

**Note**: I do not currently have an online repo and thus cannot provide the Link to Minimal Reproducible Example.

**Comment by matthewp** [comment]
I created a new project and it's working here: https://github.com/matthewp/astro-0185-is-vue-broken

If you are using an existing project make sure to update `@astrojs/renderer-vue` as well and probably also run `astro --reload`

**Comment by brycewray** [comment]
I did update `@astrojs/renderer-vue`, but hadn't tried `astro --reload` (or, in my case, `npx astro reload`). However, same result. Guess I'll `npx init astro` and start from scratch. Thanks for the reply!

**Comment by matthewp** [comment]
Good to hear, thanks!
