### ISSUE TITLE
🐛 BUG: Astro attempts to close <p> tags automatically and causes errors while doing so

### ISSUE THREAD

**Issue by okikio** [snowpackjs/astro#972]
### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

In `.astro` files if you try to enclose multiple elements in a `<p>...</p>` tag, I get this error,

```bash
[06:34:15] [snowpack] Build Result Error: There was a problem with a file build result.
[executing astro] CompileError [ParseError]: </p> attempted to close <p> that was already automatically closed by <ul>
    at error (/home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/@astrojs+parser@0.18.5/node_modules/@astrojs/parser/dist/utils/error.js:46:15)
    at Parser.error (/home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/@astrojs+parser@0.18.5/node_modules/@astrojs/parser/dist/parse/index.js:97:30)
    at tag (/home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/@astrojs+parser@0.18.5/node_modules/@astrojs/parser/dist/parse/state/tag.js:131:16)
    at new Parser (/home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/@astrojs+parser@0.18.5/node_modules/@astrojs/parser/dist/parse/index.js:57:15)
    at parse (/home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/@astrojs+parser@0.18.5/node_modules/@astrojs/parser/dist/parse/index.js:187:18)
    at convertAstroToJsx (file:///home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/astro@0.18.5/node_modules/astro/dist/compiler/index.js:37:15)
    at transformFromSource (file:///home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/astro@0.18.5/node_modules/astro/dist/compiler/index.js:72:20)
    at compileComponent (file:///home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/astro@0.18.5/node_modules/astro/dist/compiler/index.js:80:24)
    at Object.load (/home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/astro@0.18.5/node_modules/astro/snowpack-plugin.cjs:61:28)
    at async runPipelineLoadStep (/home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/snowpack@3.8.3/node_modules/snowpack/lib/cjs/build/build-pipeline.js:40:32)
    at async Object.buildFile (/home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/snowpack@3.8.3/node_modules/snowpack/lib/cjs/build/build-pipeline.js:240:24)
    at async /home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/snowpack@3.8.3/node_modules/snowpack/lib/cjs/build/file-builder.js:204:37
    at async FileBuilder.build (/home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/snowpack@3.8.3/node_modules/snowpack/lib/cjs/build/file-builder.js:216:32)
    at async Object.loadUrl (/home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/snowpack@3.8.3/node_modules/snowpack/lib/cjs/commands/dev.js:625:17)
    at async load (/home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/snowpack@3.8.3/node_modules/snowpack/lib/cjs/commands/dev.js:217:28)
    at async /home/codespace/.npm-global/pnpm-global/5/node_modules/.pnpm/snowpack@3.8.3/node_modules/snowpack/lib/cjs/ssr-loader/index.js:60:28 {
  start: { line: 54, column: 8, character: 2690 },
  end: { line: 54, column: 8, character: 2690 },
  filename: '/workspaces/bundle/temp/src/pages/index.astro',
  frame: '52:             <li><a href="https://jspm.dev" target="_blank" rel="noopener">jspm.dev</a></li>\n' +
    '53:         </ul>\n' +
    '54:         </p>\n' +
    '            ^\n' +
    '55:     </div>\n' +
    '56: </Layout>',
  __snowpackBuildDetails: { name: 'snowpack-astro', step: 'load' }
}
```

My setup is this,
```astro
---
// src/layouts/Layout.astro
let {content} = Astro.props;
content = content ?? Astro.props;

const {title, description, publishDate, author, permalink, alt} = content;
---
<html lang={ content.lang || 'en' }>
  <body>
      <slot />
  </body>
</html>

```

```astro
---
// src/pages/index.astro
import Layout from "../layouts/Layout.astro";
---

<Layout {...{
    title: 'bundle - a quick npm package size checker',
    description: "bundle is a quick and easy way to bundle, minify and gzip your projects and check said gzipped size. It's similar to bundlephobia but does all the work locally on you computer and can treeshake and bundle multiple packages (both commonjs and esm) together.",
    publishDate: 'Tuesday, June 8 2021',
    author: 'fred',
    alt: 'Astro'
}}>
    <div class="container">
        <h1>bundle</h1>
        <p>
            a quick npm package size checker <strong id="visit-counter"> </strong>
        </p>

         <!--  ... -->
         <!-- The issue is with the ending tag of the `p` element -->
        <p>
          <ul class="list-disc list-inside pt-5">
              <li><a href="https://skypack.dev" target="_blank" rel="noopener">skypack.dev</a></li>
              <li><a href="https://cdn.jsdelivr.net" target="_blank" rel="noopener">jsdelivr.net</a></li>
              <li><a href="https://esm.sh" target="_blank" rel="noopener">esm.sh</a></li>
              <li><a href="https://unpkg.com" target="_blank" rel="noopener">unpkg.com</a></li>
              <li><a href="https://jspm.dev" target="_blank" rel="noopener">jspm.dev</a></li>
          </ul>
        </p>
    </div>
</Layout>
```

### Steps to Reproduce

1. `npm init astro` using template `blog`
2. Create the files I specified above, and you should get the same error.
3. The expected behavior is that it should just work, the same way HTML would just work.

**Comment by matthewp** [comment]
I'm pretty sure this is an HTML spec thing, ul/ol is not allowed inside of p. This codepen shows the same thing happening in the browser: https://codepen.io/matthewp/pen/JjNZqva

**Comment by okikio** [comment]
> I'm pretty sure this is an HTML spec thing, ul/ol is not allowed inside of p. This codepen shows the same thing happening in the browser: https://codepen.io/matthewp/pen/JjNZqva

I didn't know about that, thanks for the help. 

Also, if you use Markdown with Astro is wraps basically everything in a paragraph tag and causes layout and styling issues, is that Markdowns expected behavior?

**Comment by jasikpark** [comment]
I've got an issue for that! 😆

**Comment by okikio** [comment]
I'll close this issue
